name: Latest blog posts
on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:
permissions:
  contents: write
jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest from my blog
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gautamkrishnar/blog-post-workflow@v1
        with:
          comment_tag_name: "BLOGPOST"
          commit_message: "Update readme with the latest blog posts"
          feed_list: "https://afrischk.github.io/atom.xml"
          template: "$newline- [$title](https://afrischk.github.io$url)"
